### ISSUE TITLE
Add documentation for including new Python modules in PATHs to run pipeline

### ISSUE THREAD

**Issue by leannehaggerty** [Ensembl/ensembl-genes#12]
Currently, to use the new RED module, we need to install it's required modules for our local python.
- do we have a better solution as we add more modules?
- can we add some documentation to the repo?

**Comment by thibauthourlier** [comment]
I think the readme would be the perfect place. People should use the requirements.txt file with pip as I don't think poetry is set up in this repo

**Comment by williamstark01** [comment]
I was going to ask at the next meeting:

Are we using one or more than one Python virtual environments? If it's just the `genebuild` one, doesn't it include all packages required by the Repeatmask_Red eHive module? And then we would activate it to run the pipeline with Python modules?

Also, now with our first brand new Python eHive module, how about generating a new Genebuild pipeline virtual environment from scratch and use Poetry to manage dependencies?

**Comment by williamstark01** [comment]
@ens-carlos

**Comment by ens-carlos** [comment]
I think that in the short term it would be better to install the packages required by Repeatmask_Red in the Python environment used by the central software repository, which is the default one used when we set up the annotation pipeline. If we are using local Python environments we should try to stick to just using one or if we use more than one to make them work automatically when we set up and run things so we don't have to manually change environments or set them up every time we start or make progress on any annotation project. Also, whatever way we go forward, we should remove the other options so we don't get Python environments and configs mixed. For example, if we use local Python set ups by default, we should find a way to disable the set up pointing to the central Python by removing it from the system paths, python paths, etc.

**Comment by thibauthourlier** [comment]
First at the moment, the software for the pipeline should all be in the central environment. But with the new cluster coming, I would push to not have python centralised because that mean having 2 pyenv for most people which can cause more problems.
Once we are getting close to having an automated pipeline, we can look to have a shared (central for genebuild) production environment to run the pipelines and dev environments for any other projects.
For the software we create it is easy to enforce only one environment, for software we don't it's not that easy. For example, the current ncRNA pipeline needs specific versions of libraries which means that any other python software we use would need to work with these older versions... One solution is using containers which needs to be created. Some are being created or have already been created.
Nothing stops you from either do symlinks to the central python install or to install the software you need in your own pyenv

**Comment by williamstark01** [comment]
I agree with @ens-carlos points that the use of Python virtual environments should be transparent, and not spend time setting up things manually.

I also agree with @thibauthourlier that it's probably for the best to not have a centralized Python installation in the new cluster, it just complicates things.

For now, the best option for running the eHive Python modules is in my view using Genebuild-wide virtual environments that we manage on our own, and simply using symlinks to them to import them to our own pyenv setup. I also propose we create them using Poetry, so we can generate them and update packages deterministically.

The advantages to using Genebuild-wide venvs is that we will not have to think about them, even after occasionally updating their dependencies. We can also include the symlink generation commands in the pipeline setup script, so their use would be completely automatic to us when running a pipeline.

Does that make sense to you?

**Comment by thibauthourlier** [comment]
@ens-carlos, does the current requirements.txt file have all dependencies? I can add it to the central software

I may forget but if people remind me or create a ticket for me I can install any software, no need for having virtualenv everywhere. As long as the Codon stuff is not agreed, I would prefer to keep the current setting and not start something which we will have to ditch in 3 months.
